window.ACTOR_DEFS = {
  louis14:{code:'LOUIS XIV',name:'루이 14세',group:'france'},
  anne_louis:{code:'QUEEN ANNE',name:'앤의 몸에 든 루이',group:'england'},
  robert:{code:'ROYAL STEWARD',name:'로버트',group:'england'},
  mp_leader:{code:'PARLIAMENT',name:'영국 의회 대표',group:'parliament'},
  mp_secondary:{code:'PARLIAMENT',name:'영국 의원',group:'parliament'},
  parlement_rep:{code:'PARLEMENT DE PARIS',name:'파리 고등법원 대표',group:'france'},
  french_official:{code:'ROYAL OFFICIAL',name:'프랑스 관리',group:'france'},
  french_general:{code:'ROYAL ARMY',name:'프랑스 장군',group:'france'},
  french_reporter:{code:'DIPLOMATIC REPORT',name:'보고관',group:'france'},
  english_general:{code:'WAR REPORT',name:'영국 장군',group:'england'},
  maid:{code:'ROYAL HOUSEHOLD',name:'시녀',group:'england'},
  elizabeth:{code:'ELIZABETH I',name:'엘리자베스 1세',group:'memory'},
  james1:{code:'JAMES I',name:'제임스 1세',group:'memory'},
  charles1:{code:'CHARLES I',name:'찰스 1세',group:'memory'},
  james2:{code:'JAMES II',name:'제임스 2세',group:'memory'},
  unknown:{code:'???',name:'???',group:'unknown'}
};

const S=(...actors)=>actors.map(([id,slot])=>({id,slot}));
window.STAGE_MAP = {
  'scene-01':S(['french_official','left'],['louis14','center'],['french_general','right']),
  'scene-02':S(['louis14','left'],['parlement_rep','right']),
  'scene-03':S(['louis14','center']),
  'scene-04':S(['louis14','left'],['french_reporter','right']),
  'scene-05':S(['louis14','left'],['unknown','right']),
  'scene-06':S(['anne_louis','left'],['maid','center'],['robert','right']),
  'scene-07':S(['anne_louis','left'],['maid','center'],['robert','right']),
  'scene-08':S(['anne_louis','left'],['robert','right']),
  'scene-09':S(['anne_louis','left'],['robert','right']),
  'scene-10':S(['anne_louis','left'],['mp_leader','right']),
  'scene-11':S(['anne_louis','left'],['robert','right']),
  'scene-12':S(['anne_louis','left'],['robert','right']),
  'scene-13':S(['anne_louis','left']),
  'scene-14':S(['anne_louis','left'],['elizabeth','center'],['mp_leader','right']),
  'scene-15':S(['anne_louis','left']),
  'scene-16':S(['anne_louis','left'],['robert','right']),
  'scene-17':S(['anne_louis','left'],['mp_leader','right']),
  'scene-18':S(['anne_louis','left'],['robert','right']),
  'scene-19':S(['anne_louis','left']),
  'scene-20':S(['anne_louis','left'],['james1','center'],['charles1','right']),
  'scene-21':S(['anne_louis','left']),
  'scene-22':S(),
  'scene-23':S(['anne_louis','left'],['robert','center'],['english_general','right']),
  'scene-24':S(['anne_louis','left'],['mp_leader','right']),
  'scene-25':S(['anne_louis','left'],['robert','right']),
  'scene-26':S(['anne_louis','left']),
  'scene-27':S(['anne_louis','left'],['james2','right']),
  'scene-28':S(['anne_louis','left'],['james2','center'],['mp_leader','right']),
  'scene-29':S(['anne_louis','left'],['robert','right']),
  'scene-30':S(['anne_louis','left'],['mp_leader','right']),
  'scene-31':S(['anne_louis','left'],['mp_leader','right']),
  'scene-32':S(['anne_louis','left'],['mp_leader','right']),
  'scene-33':S(['anne_louis','left'],['mp_leader','right']),
  'scene-34':S(['anne_louis','left'],['mp_leader','right']),
  'scene-35':S(['anne_louis','left'],['robert','right']),
  'scene-36':S(['anne_louis','center']),
  'scene-37':S(['anne_louis','center']),
  'scene-38':S(['louis14','left'],['french_reporter','right']),
  'scene-39':S(['louis14','left'],['french_reporter','right']),
  'scene-40':S(['louis14','center'])
};
